name: Go

on: [push]

jobs:
  build-api-gateway:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .
        working-directory: ./http/handler-apigtw

      - name: Build
        run: go build -v ./...
        working-directory: ./http/handler-apigtw

  build-homepage:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .
        working-directory: ./http/handler-home

      - name: Build
        run: go build -v ./...
        working-directory: ./http/handler-home

  build-aboutpage:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .
        working-directory: ./http/handler-about

      - name: Build
        run: go build -v ./...
        working-directory: ./http/handler-about